// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "FinAdvise",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import AuthProvider from "../utils/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider session={session}>
        <div className="mx-auto text-xl  mb-10"> 
            {children}
         </div>  
        </AuthProvider>
      </body>
    </html>
  );
}
